### PR TITLE
Improve readme.md

### PR DESCRIPTION
**Pull request by Vinit-Code04**
I add some  additional information, I hope its help you.

### CODE REVIEW

**Comment by sansyrox** [comment]
@Vinit-Code04 , I've made some changes. looks good overall 🔥

**Comment by Vinit-Code04** [comment]
Thank you

**Comment by Vinit-Code04** [comment]
Sir Please label this pull request as Hacktoberfest Please

**Comment by sansyrox** [comment]
@Vinit-Code04 , done 👍

**Comment by Vinit-Code04** [comment]
Thanks a lot

**Pull request merged**
